# General
set -g default-terminal "screen-256color"
set -g history-limit 5000

# Reload configs
unbind r
bind r source-file ~/.tmux.conf \; display-message "Config reloaded"

# Ctrl + space as prefix
set -g prefix C-Space
unbind C-b
bind C-Space send-prefix
bind C-Space last-window

# Resize
bind C-h resize-pane -L 4
bind C-j resize-pane -D 4
bind C-k resize-pane -U 4
bind C-l resize-pane -R 4

# Fire focus event
set -g focus-events on

# Fire command with no delay
set -g repeat-time 0

# Mouse mode off
set -g mouse off

# Start window and pane at 1 (default 0)
set-option -g base-index 1
setw -g pane-base-index 1

# Status Bar
set-option -g status on
set-option -g status-position top
set -g status-interval 5
set -g status-justify centre
setw -g monitor-activity on
setw -g automatic-rename on
set -g status-style 'fg=white bg=black'
set -g message-style 'fg=black nobold bg=green bold'
set -g status-right ''
set -g status-left '#S'
set -g window-status-format " #I #W "
set -g window-status-current-format "#[fg=colour234,bg=colour109] #I <#W> "
set -g window-status-activity-style 'fg=black nobold bg=green bold'
