#!/bin/sh

set -e

DOTFILES_DIR="$(cd "$(dirname "$0")" && pwd)"

stow_to() {
  target="$1"; pkg="$2"
  mkdir -p "$target"
  stow --target "$target" --dir "$DOTFILES_DIR" --restow "$pkg"
}

stow_to "$HOME"                 home
stow_to "$HOME/.config/zsh"     zsh
stow_to "$HOME/.config/nvim"    nvim
stow_to "$HOME/.config/tmux"    tmux
stow_to "$HOME/.config/ghostty" ghostty

echo "Done!"
