# general
set -g default-terminal "screen-256color"
set -g history-limit 5000

# ctrl-space as prefix
set -g prefix C-Space
unbind-key C-b
bind-key C-Space send-prefix
bind-key C-Space last-window

# mouse mode on
set -g mouse on

# for auto read
set -g focus-events on

# start window and pane at 1, not 0
set-option -g base-index 1
setw -g pane-base-index 1

# resize window
bind-key -n C-S-Left resize-pane -L 5
bind-key -n C-S-Right resize-pane -R 5
bind-key -n C-S-Up resize-pane -U 5
bind-key -n C-S-Down resize-pane -D 5

# Status Bar
set-option -g status on
set -g status-interval 5
set -g status-justify centre

setw -g monitor-activity on
setw -g automatic-rename on

set -g status-style 'fg=white bg=black'
set -g message-style 'fg=colour234 nobold bg=colour143 bold'
set -g status-right ''
set -g status-left '#S'
set -g window-status-format " #I #W "
set -g window-status-current-format "#[fg=colour234,bg=colour109] #I <#W> "
set -g window-status-activity-style 'bg=yellow,bold,fg=black,nobold'
