background {
    color = rgb(000000)
}

input-field {
    size = 250, 40
    outline_thickness = 1
    outer_color = rgb(ffffff)
    inner_color = rgb(000000)
    font_color = rgb(ffffff)
    fade_on_empty = true
    fade_timeout = 0
    placeholder_text =
    halign = center
    valign = center
}
