background {
    color = rgba(0, 0, 0, 1)
}

input-field {
    size = 300, 50
    outline_thickness = 2
    outer_color = rgb(255, 255, 255)
    inner_color = rgb(0, 0, 0)
    font_color = rgb(255, 255, 255)
    placeholder_text = Password
}
