general {
    gaps_in = 0
    gaps_out = 0
    border_size = 1
    col.active_border = rgb(ffffff)
    col.inactive_border = rgb(444444)
}

decoration {
    rounding = 2
    blur {
        enabled = false
    }
    shadow {
        enabled = false
    }
}

animations {
    enabled = false
}
