general {
    gaps_in = 0
    gaps_out = 0
    border_size = 1
    col.active_border = rgb(ffffff)
    col.inactive_border = rgb(333333)
}

decoration {
    rounding = 0

    blur {
        enabled = false
    }

    shadow {
        enabled = false
    }
}

animations {
    enabled = true

    animation = windows, 1, 1.5, default
    animation = windowsOut, 1, 1.5, default, popin 80%
    animation = fade, 1, 1.5, default
    animation = workspaces, 1, 1.5, default
}

dwindle {
    preserve_split = true
}

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
}
